USE logistica;

/* Fórmula para calcular os dias em atraso*/
/* se o pacote já tiver embarcado verifica se houve atraso*/
/* se o pacote não tiver embarcado verifica o prazo restante*/
UPDATE SHIPPING_INFO
SET DIAS_ATRASO_ = 
    CASE 
        WHEN DATA_EMBARQUE_ IS NOT NULL THEN DATEDIFF(DAY, DATA_MAXIMA_DESEMBARQUE_, DATA_EMBARQUE_)
        ELSE DATEDIFF(DAY, DATA_MAXIMA_DESEMBARQUE_, GETDATE())
    END;

/* ALGUM PRODUTO EMBARCOU DEPOIS DA DATA DE VALIDADE?*/
SELECT NUMERO_CARGA, DATA_EMBARQUE_, DATA_VALIDADE_ 
FROM SHIPPING_INFO
WHERE DATA_MAXIMA_DESEMBARQUE_ > DATA_VALIDADE_;

/* ALGUM PRODUTO ATRASOU O AMBARQUE?*/
SELECT NUMERO_CARGA, DATA_MAXIMA_DESEMBARQUE_,DATA_EMBARQUE_
FROM SHIPPING_INFO
WHERE DATA_EMBARQUE_ > DATA_MAXIMA_DESEMBARQUE_;

/* QUAL A MÉDIA DE PESO QUE CADA PORTO RECEBE/ ORDENADO */
SELECT PORTO_DESTINO, AVG(PESO_KG_) AS PESO_MEDIO 
FROM SHIPPING_INFO 
GROUP BY PORTO_DESTINO
ORDER BY PESO_MEDIO;

/* ALOCAR PRODUTOS QUE AINDA NÃO FORAM EMBARCADOS EM NAVIOS QUE AINDA IRÃO PASSAR*/

SELECT ID_NAVIO, NUMERO_CARGA,  SF.PORTO_DESTINO AS PORTO_DESTINO, DATA_EMBARQUE, DATA_DESEMBARQUE,
    CASE 
        WHEN SF.DATA_EMBARQUE_ IS NULL THEN SF.DATA_MAXIMA_DESEMBARQUE_
        ELSE NULL
    END AS DATA_MAXIMA_DESEMBARQUE_
FROM SHIPPING_INFO SF 
JOIN SHIP_SCHEDULE SS ON SF.PORTO_DESTINO = SS.PORTO_DESTINO
WHERE DATA_MAXIMA_DESEMBARQUE_<=DATA_DESEMBARQUE;

/* CARGA QUE VAI PARA O MESMO PORTO MAS NÃO PODE SER ALOCADA POR CONTA DA DATA*/
SELECT ID_NAVIO, NUMERO_CARGA,  SF.PORTO_DESTINO AS PORTO_DESTINO, DATA_EMBARQUE, DATA_DESEMBARQUE,
    CASE 
        WHEN SF.DATA_EMBARQUE_ IS NULL THEN SF.DATA_MAXIMA_DESEMBARQUE_
        ELSE NULL
    END AS DATA_MAXIMA_DESEMBARQUE_
FROM SHIPPING_INFO SF 
JOIN SHIP_SCHEDULE SS ON SF.PORTO_DESTINO = SS.PORTO_DESTINO
WHERE  DATA_MAXIMA_DESEMBARQUE_>DATA_DESEMBARQUE;



